# Generated by Django 6.0 on 2026-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsettings',
            name='requests_per_minute',
            field=models.PositiveIntegerField(default=12, help_text="Max Gemini requests per minute across every server this bot is in. All chat requests go through a single queue that waits between calls to respect this limit — keep it a bit under your API key's actual quota (the free tier is 15/min). Raise this if you're on a paid plan."),
        ),
    ]
