# Generated by Django 6.0 on 2026-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_alter_aichatsettings_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsettings',
            name='music_api_key',
        ),
        migrations.RemoveField(
            model_name='aichatsettings',
            name='music_api_url',
        ),
        migrations.AddField(
            model_name='aichatsettings',
            name='allow_artwork',
            field=models.BooleanField(default=False, help_text="Let the AI fetch and post a released collectible's artwork in chat. OFF by default to avoid leaking images of rare or unreleased collectibles."),
        ),
        migrations.AddField(
            model_name='aichatsettings',
            name='allow_stats_lookup',
            field=models.BooleanField(default=False, help_text="Let the AI look up and search released collectibles' stats (rarity, health, attack, capacity) by name. OFF by default to avoid leaking details of rare or unreleased collectibles."),
        ),
        migrations.AddField(
            model_name='aichatsettings',
            name='allow_web_search',
            field=models.BooleanField(default=False, help_text="Let the AI search the web (via Gemini's built-in Google Search grounding) to answer questions with current information. OFF by default. Requires a model that supports search grounding; if a request fails with it on, the bot automatically retries without it."),
        ),
        migrations.AddField(
            model_name='aichatsettings',
            name='fallback_models',
            field=models.TextField(blank=True, default='gemini-2.5-flash', help_text="Semicolon-separated backup model IDs, tried in order if the primary model fails or hits its quota. Each free model has its own separate daily allowance, so listing another one keeps the bot working after the primary's quota runs out. Leave empty to disable fallback."),
        ),
        migrations.AlterField(
            model_name='aichatsettings',
            name='model',
            field=models.CharField(default='gemini-2.5-flash-lite', help_text="Primary Gemini model ID used for chat (see ai.google.dev/gemini-api/docs/models). A '-lite' model is recommended: on the free tier it gives far more requests per day than the full Flash models (e.g. ~500/day at 15/min vs ~20/day). Check your live limits in Google AI Studio.", max_length=64),
        ),
    ]
