# Generated by Django 6.0 on 2026-07-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0004_remove_aichatsettings_music_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsettings',
            name='allow_web_search',
            field=models.BooleanField(default=False, help_text="Let the AI search the web (via Gemini's built-in Google Search grounding) to answer with current information. OFF by default. On the free tier, search grounding only works on Gemini 2.x models (~1,500 searches/day) — NOT on Gemini 3.x. If your chat model doesn't support it, the bot automatically retries without search rather than failing."),
        ),
        migrations.AlterField(
            model_name='aichatsettings',
            name='fallback_models',
            field=models.TextField(blank=True, default='gemini-2.5-flash-lite', help_text='Semicolon-separated backup model IDs, tried in order if the primary fails or hits its quota. Each free model has its own separate daily allowance, so this both survives an outdated primary model ID and stacks extra daily capacity. Leave empty to disable fallback.'),
        ),
        migrations.AlterField(
            model_name='aichatsettings',
            name='model',
            field=models.CharField(default='gemini-3.1-flash-lite', help_text='Primary Gemini model ID used for chat (see ai.google.dev/gemini-api/docs/models). gemini-3.1-flash-lite is the best free-tier chat pick by far — ~500 requests/day at 15/min, versus ~20/day for the full Flash models. Copy the exact ID from Google AI Studio if this errors.', max_length=64),
        ),
    ]
