# Generated by Django 6.0 on 2026-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0005_alter_aichatsettings_allow_web_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsettings',
            name='fallback_models',
            field=models.TextField(blank=True, default='', help_text="Optional semicolon-separated backup model IDs, tried in order if the primary fails or hits its quota. Each free model has its own separate daily allowance, so a backup both survives an outdated primary ID and stacks extra daily capacity. Empty by default — gemini-3.1-flash-lite's ~500/day is plenty for most bots. Only add IDs you've confirmed exist on your account."),
        ),
        migrations.AlterField(
            model_name='aichatsettings',
            name='model',
            field=models.CharField(default='gemini-3.1-flash-lite', help_text='Primary Gemini model ID used for chat (see ai.google.dev/gemini-api/docs/models). gemini-3.1-flash-lite is the best free-tier chat pick by far — ~500 requests/day at 15/min, versus ~20/day for the full Flash models. If this returns a 404, the ID has changed — copy the exact one from Google AI Studio (model IDs get retired over time; e.g. gemini-2.5-flash-lite is already gone).', max_length=64),
        ),
    ]
