# Generated by Django 6.0 on 2026-07-20 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0006_alter_aichatsettings_fallback_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsettings',
            name='allowed_channel_ids',
            field=models.TextField(blank=True, default='', help_text='Semicolon-separated SERVER channel IDs where the bot may chat. Leave empty to allow any channel it can see. Direct messages always work regardless of this list — it only restricts server channels. (The bot still only replies when mentioned or DMed.)', validators=[django.core.validators.RegexValidator('^(\\d{17,21}(;\\d{17,21})*)?$', message='The IDs must be semicolon-separated')]),
        ),
        migrations.AlterField(
            model_name='aichatsettings',
            name='max_history',
            field=models.PositiveIntegerField(default=12, help_text='How many past messages to send as context per reply (only counts actual bot conversations, so 12 ≈ 6 back-and-forth exchanges). Higher means better memory but more tokens per reply — the main cost lever if you move to a paid tier.'),
        ),
    ]
