# Generated by Django 6.0 on 2026-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0007_alter_aichatsettings_allowed_channel_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsettings',
            name='fallback_models',
            field=models.TextField(blank=True, default='gemini-3.5-flash-lite', help_text="Semicolon-separated backup model IDs, tried in order if the primary fails or hits its quota. Each free model has its own separate daily allowance, so a backup both survives an outdated primary ID and stacks extra daily capacity. gemini-3.5-flash-lite has the exact same free-tier limits as the default primary model (~500/day, 15/min) and its own separate quota, so this roughly doubles daily headroom for free. Clear it if you don't want that; only add IDs you've confirmed exist on your account."),
        ),
    ]
