# Generated by Django 6.0 on 2026-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0009_alter_aichatsettings_fallback_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsettings',
            name='allow_special_events',
            field=models.BooleanField(default=False, help_text="Let the AI list your special events — every event that isn't hidden, each marked as currently active or not. Hidden events are never included. OFF by default: even a non-hidden event you haven't announced yet would be listed."),
        ),
    ]
