# Generated by Django 6.0 on 2026-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0010_aichatsettings_allow_special_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsettings',
            name='requests_per_minute',
            field=models.PositiveIntegerField(default=12, help_text="Max Gemini API requests per minute across every server this bot is in. Keep it a bit under your API key's actual quota (the free tier is 15/min). Note this counts API requests, not replies: one reply costs one request, plus one more for each round of tool use, so a reply that looks something up typically costs 2. At the default of 12 that's roughly 6 such replies a minute. Raise this if you're on a paid plan."),
        ),
    ]
